name: dart_frog_playground_firebase
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  firebase_dart: ^1.0.11
  jaguar_jwt: ^3.0.0
  mongo_dart: ^0.7.4+1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
